import user from '@/assets/images/svgs/user.png';
import logoDark from '@/assets/images/brand-logos/desktop-logo-dark.png';
import logoLight from '@/assets/images/brand-logos/desktop-logo-dark.png';
import flag1 from '@/assets/images/flags/1.jpg';
import flag2 from '@/assets/images/flags/2.jpg';
import flag3 from '@/assets/images/flags/3.jpg';
import flag4 from '@/assets/images/flags/4.jpg';
import flag5 from '@/assets/images/flags/5.jpg';
import flag6 from '@/assets/images/flags/6.jpg';

export const user_logo = user;
export const logo_light = logoLight;
export const main_logo_dark = logoDark;
export const main_logo_light = logoLight;
export const image_flag1 = flag1;
export const image_flag2 = flag2;
export const image_flag3 = flag3;
export const image_flag4 = flag4;
export const image_flag5 = flag5;
export const image_flag6 = flag6;
